a = int(input("enter a number"))
b = int(input("enter another number"))
print("this is a XOR oparator:")
print(a^b)
print("this is a AND oparator:")
print(a&b)
print("this is a OR oparator:")
print(a|b)
print("this is a NOT oparator:")
print(~a)
